### PR TITLE
porting to .NET 5.0

### PR DESCRIPTION
**Pull request by MovGP0**
• Ported the Math-Editor to .NET 5.0. 
• Cleaned up .csproj file
• Deleted duplicated files

### CODE REVIEW

**Comment by kashifimran** [comment]
Hi. I no longer have access to a windows machine and .Net build tools. Have you tested and does it work as expected? 
Thanks for the effort you put there!

**Comment by MovGP0** [comment]
Yes, I've tested it. With the exception of opening external links everything seems fine. Might fix this issue in a later version. 

https://github.com/dotnet/corefx/issues/10361

**Comment by MovGP0** [comment]
Issue was fixed. Some of the URLs do not exist anymore and there is a threading issue with the caret blinking, when the application is closed and the caret is disposed. Might fix those later, but those bugs are in the current version as well.

**Comment by MovGP0** [comment]
> Hi. I no longer have access to a windows machine and .Net build tools. 

I might be able to port the project to [Avalonia](https://avaloniaui.net/), such that it works on Linux and MacOS too. But won't be able to test on those plattforms.

**Comment by kashifimran** [comment]
Merged. Thanks for your effort again. I think it is still helping students. So a good effort. I have not worked in C# for 5 years now. I hardly remember the code any more. There's a bug in the undo/redo that causes issue. I am not aware of any threading bug in the caret though.

**Pull request merged**
